"""Add credential vault

Revision ID: 096d948c5dbd
Revises: e66ba2abd991
Create Date: 2025-02-18 22:43:17.208289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096d948c5dbd'
down_revision = 'e66ba2abd991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.String(length=20), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credential_vault')
    # ### end Alembic commands ###
