"""Add CloudCredentials model

Revision ID: a3733bc6f573
Revises: aab9b807996b
Create Date: 2025-02-16 17:02:44.198149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3733bc6f573'
down_revision = 'aab9b807996b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('icloud_username', sa.String(length=120), nullable=True),
    sa.Column('icloud_password', sa.String(length=256), nullable=True),
    sa.Column('aws_access_key', sa.String(length=128), nullable=True),
    sa.Column('aws_secret_key', sa.String(length=256), nullable=True),
    sa.Column('s3_bucket', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_credentials')
    # ### end Alembic commands ###
