"""Update credential vault schema

Revision ID: b482e1c8ceb0
Revises: 096d948c5dbd
Create Date: 2025-02-18 22:46:25.776549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b482e1c8ceb0'
down_revision = '096d948c5dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_vault', schema=None) as batch_op:
        batch_op.create_index('idx_user_credential_type', ['user_id', 'credential_type'], unique=True)
        batch_op.drop_constraint('credential_vault_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_vault', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('credential_vault_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_index('idx_user_credential_type')

    # ### end Alembic commands ###
