"""Initial migration

Revision ID: e66ba2abd991
Revises: a3733bc6f573
Create Date: 2025-02-16 17:36:42.936549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e66ba2abd991'
down_revision = 'a3733bc6f573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_credentials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('icloud_username', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('icloud_password', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('aws_access_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('aws_secret_key', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('s3_bucket', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cloud_credentials_pkey')
    )
    # ### end Alembic commands ###
